name: CI

on:
  push:
    branches: ['main']
    tags:
      - "v*"
  pull_request:
    branches: ['main']

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.2.3)'
        required: false
        default: ''

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag || github.ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: make install
    - run: make test

  release:
    if: ${{ github.event.inputs.tag != '' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-24.04
    needs: ['test']
    permissions:
      contents: write
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set version env
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - uses: release-drafter/release-drafter@v5
        with:
          name: ${{ env.RELEASE_VERSION }}
          tag: ${{ env.RELEASE_VERSION }}
          version: ${{ env.RELEASE_VERSION }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make install
      - working-directory: ./js
        run: |
          make build
          npx jsr publish --allow-slow-types
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
